POST http://localhost:3000/login
content-type: application/json

{
    "username": "tom",
    "password": "2222"
}

### create jwt
GET http://localhost:3000/jwt
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MTM2MTIzMjgsImV4cCI6MTYxMzY5ODcyOH0.WraBygnQbPJnW-Bd-g4aQ2e97x0v735ATLY3wzRTBvU

### jwt verify
GET http://localhost:3000/blog
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MTM2MTIzMjgsImV4cCI6MTYxMzY5ODcyOH0.WraBygnQbPJnW-Bd-g4aQ2e97x0v735ATLY3wzRTBvU

### hash password
GET http://localhost:3000/password/2222

### delete post
DELETE http://localhost:3000/blog/5
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MTM2MTIzMjgsImV4cCI6MTYxMzY5ODcyOH0.WraBygnQbPJnW-Bd-g4aQ2e97x0v735ATLY3wzRTBvU